# Generated by Django 3.1.4 on 2021-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_file'),
        ),
        migrations.AlterField(
            model_name='mandi',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
