# Generated by Django 3.1.4 on 2021-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='connected_to',
            field=models.ManyToManyField(blank=True, related_name='_cities_connected_to_+', to='core.Cities'),
        ),
    ]
